// Our move id -> slug in the Workout Guide library (github.com/bryllim/workout-guide, assets CC BY-SA 4.0).
// Moves without an entry have no picture there: office moves (neck, wrist, eyes, chair and desk work) stay without a drawing for now.
export const WG = {
  squat: 'bodyweight-squat',
  'jump-squat': 'jump-squat',
  'calf-raise': 'calf-raise',
  'wall-sit': 'wall-sit',
  'reverse-lunge': 'reverse-lunge',
  'forward-lunge': 'forward-lunge',
  'desk-pushup': 'incline-push-up',
  pushup: 'push-up',
  'diamond-pushup': 'diamond-push-up',
  'knee-pushup': 'knee-push-up',
  'wall-pushup': 'wall-push-up',
  'chair-dip': 'chair-dip',
  plank: 'plank',
  'shoulder-taps': 'plank-shoulder-tap',
  'mountain-climber': 'mountain-climber',
  'jumping-jacks': 'jumping-jack',
  burpee: 'burpee',
  inchworm: 'inchworm',
  'high-knees': 'high-knees',
  'glute-bridge': 'glute-bridge',
  crunch: 'crunch',
  'bicycle-crunch': 'bicycle-crunch',
  'leg-raise': 'lying-leg-raise',
  superman: 'superman',
  'bird-dog': 'bird-dog',
  'childs-pose': 'childs-pose',
  'quad-stretch': 'standing-quad-stretch',
  'wall-chest-stretch': 'doorway-chest-stretch',
  'seated-knee-lift': 'seated-knee-tuck',
  'db-curl': 'bicep-curl',
  'db-press': 'standing-dumbbell-press',
  'db-goblet-squat': 'goblet-squat',
  'db-row': 'dumbbell-bent-over-row',
  'db-rdl': 'dumbbell-romanian-deadlift',
  'db-tricep-ext': 'dumbbell-overhead-tricep-extension',
  'band-row': 'banded-row',
  'kb-swing': 'kettlebell-swing',
  pullup: 'pull-up',
  'dead-hang': 'dead-hang',
}
