// Turkish for every text in the plugin. The English text is the key; `npm run i18n` lists any that are missing.
export const TR: Record<string, string> = {
  "Chair squats": "Sandalye squat'ı",
  "Bodyweight squats": "Vücut ağırlığıyla squat",
  "Jump squats": "Sıçramalı squat",
  "Calf raises": "Baldır kaldırma",
  "Wall sit": "Duvar oturuşu",
  "Reverse lunges": "Geriye hamle",
  "Standing glute squeezes": "Ayakta kalça sıkma",
  "Desk push-ups": "Masada şınav",
  "Push-ups": "Şınav",
  "Diamond push-ups": "Elmas şınav",
  "Chair dips": "Sandalyede dips",
  "Wall angels": "Duvar melekleri",
  "Plank": "Plank",
  "Knee plank": "Dizli plank",
  "Seated knee lifts": "Oturarak diz kaldırma",
  "Mountain climbers": "Dağ tırmanışı",
  "Standing crunches": "Ayakta crunch",
  "Seated twists": "Oturarak gövde çevirme",
  "Seated cat-cow": "Oturarak kedi-inek",
  "Hip hinges": "Kalça menteşesi",
  "Neck rolls": "Boyun çevirme",
  "Chin tucks": "Çene çekme",
  "Shoulder rolls": "Omuz çevirme",
  "Wrist and finger stretch": "Bilek ve parmak esnetme",
  "Prayer stretch": "Dua esnetmesi",
  "20-20-20 eye break": "20-20-20 göz molası",
  "Jumping jacks": "Jumping jack",
  "Marching in place": "Yerinde yürüyüş",
  "Burpees": "Burpee",
  "Stand in front of your chair, sit back until you touch it, stand up. Keep your chest tall.": "Sandalyenin önünde dur, ona değene kadar geriye otur, sonra ayağa kalk. Göğsünü dik tut.",
  "Feet shoulder-width, sit back and down, thighs parallel, drive up through your heels.": "Ayaklar omuz genişliğinde, kalçanı geriye ve aşağı indir, uyluklar yere paralel olsun, topuklarından iterek kalk.",
  "Squat, then explode up and land softly. Reset between reps.": "Çömel, sonra patlayıcı şekilde zıpla ve yumuşak in. Tekrarlar arasında toparlan.",
  "Stand tall, rise onto your toes, lower slowly. Hold the desk for balance.": "Dik dur, parmak uçlarına yüksel, yavaşça in. Dengen için masaya tutun.",
  "Back flat on the wall, thighs parallel to the floor. Hold.": "Sırtın duvara yaslı, uyluklar yere paralel. Pozisyonu koru.",
  "Step back, lower the back knee toward the floor, push up. Alternate legs.": "Geriye adım at, arka dizini yere doğru indir, yukarı it. Bacakları değiştir.",
  "Stand tall, squeeze your glutes hard for 3 seconds, release. Repeat.": "Dik dur, kalçalarını 3 saniye sıkıca sık, bırak. Tekrarla.",
  "Hands on the desk edge, body straight, lower your chest to the desk and press back.": "Ellerin masanın kenarında, vücudun düz, göğsünü masaya indir ve geri it.",
  "Hands under shoulders, body in one line, chest to the floor, press up.": "Eller omuz altında, vücut tek çizgide, göğsünü yere indir ve yukarı it.",
  "Hands form a diamond under your chest. Lower slowly, press up.": "Eller göğsünün altında elmas şekli oluştursun. Yavaşça in, yukarı it.",
  "Hands on the seat edge, legs forward, lower your hips by bending the elbows, press up.": "Eller sandalye kenarında, bacaklar önde, dirseklerini bükerek kalçanı indir, yukarı it.",
  "Back and arms against a wall, slide your arms up and down like a snow angel.": "Sırtın ve kolların duvara yaslı, kollarını kar meleği gibi yukarı aşağı kaydır.",
  "Forearms down, body in one straight line, brace your core and breathe.": "Ön kollar yerde, vücut tek düz çizgide, karnını sık ve nefes al.",
  "Same as a plank, but with knees on the floor. Keep hips in line.": "Plank ile aynı, ama dizler yerde. Kalçanı hizada tut.",
  "Sit tall, hold the seat, lift both knees toward your chest, lower slowly.": "Dik otur, sandalyeyi tut, iki dizini göğsüne doğru kaldır, yavaşça indir.",
  "High plank, drive your knees to your chest in a quick run.": "Yüksek plankta, dizlerini hızlı bir koşu gibi göğsüne çek.",
  "Hands behind your head, lift one knee and bring the opposite elbow to it. Alternate.": "Eller başının arkasında, bir dizini kaldır ve karşı dirseği ona yaklaştır. Sırayla yap.",
  "Sit tall, rotate your torso gently left and right, hips facing forward.": "Dik otur, gövdeni nazikçe sola ve sağa çevir, kalçan öne baksın.",
  "Hands on knees, arch your back and look up, then round it and tuck your chin.": "Eller dizlerde, sırtını kavisle ve yukarı bak, sonra yuvarla ve çeneni içeri al.",
  "Hands on hips, push your hips back with a flat spine, return upright.": "Eller belde, sırtın düz, kalçanı geriye doğru it, sonra dik duruşa dön.",
  "Slowly drop your ear to each shoulder, then chin to chest. No full circles.": "Kulağını yavaşça sırayla her omzuna, sonra çeneni göğsüne indir. Tam daire çizme.",
  "Draw your chin straight back as if making a double chin. Hold 3 seconds, release.": "Çeneni çift çene yapar gibi düz geriye çek. 3 saniye tut, bırak.",
  "Roll your shoulders big and slow, forward then backward.": "Omuzlarını büyük ve yavaş şekilde önce ileri, sonra geri çevir.",
  "Circle your wrists both ways, then stretch fingers wide and make a soft fist.": "Bileklerini iki yöne çevir, sonra parmaklarını aç ve hafifçe yumruk yap.",
  "Palms together at chest height, lower your hands slowly until you feel the forearm stretch.": "Avuç içleri göğüs hizasında birleşik, ön kolda esneme hissedene kadar ellerini yavaşça indir.",
  "Look at something 20 feet (6 m) away. Blink slowly and let your eyes relax.": "6 metre uzaktaki bir şeye bak. Yavaşça göz kırp ve gözlerini dinlendir.",
  "Jump feet out while raising your arms, jump back in. Keep a steady rhythm.": "Kollarını kaldırırken ayaklarını açarak zıpla, sonra kapat. Düzenli bir tempo tut.",
  "Lift your knees to hip height and swing your arms. Keep it brisk.": "Dizlerini kalça hizasına kaldır ve kollarını salla. Tempoyu canlı tut.",
  "Squat, kick back to plank, push-up, jump in, jump up.": "Çömel, plank pozisyonuna atla, şınav çek, ayakları geri getir, yukarı zıpla.",
  "legs": "bacak",
  "core": "karın",
  "upper": "üst vücut",
  "back": "sırt",
  "neck": "boyun",
  "wrists": "bilekler",
  "eyes": "gözler",
  "full": "tüm vücut",
  "beginner": "başlangıç",
  "intermediate": "orta",
  "advanced": "ileri",
  "First step": "İlk adım",
  "Finish your first set": "İlk setini bitir",
  "Warm engine": "Isınan motor",
  "10 sets in total": "Toplam 10 set",
  "Century": "Yüzlük",
  "100 sets in total": "Toplam 100 set",
  "On a roll": "Formdasın",
  "3 day streak": "3 günlük seri",
  "Full week": "Tam hafta",
  "7 day streak": "7 günlük seri",
  "Habit formed": "Alışkanlık oldu",
  "30 day streak": "30 günlük seri",
  "Build break": "Derleme molası",
  "Do a set while Claude is working": "Claude çalışırken bir set yap",
  "Compile and conquer": "Derle ve fethet",
  "10 sets while Claude is working": "Claude çalışırken 10 set",
  "All-rounder": "Çok yönlü",
  "5 different body areas in one week": "Bir haftada 5 farklı vücut bölgesi",
  "Early bird": "Erkenci",
  "A set before 9 am": "Sabah 9'dan önce bir set",
  "Hour of power": "Güç saati",
  "60 active minutes in total": "Toplam 60 aktif dakika",
  "General fitness": "Genel kondisyon",
  "Lose weight": "Kilo vermek",
  "Build strength": "Güç kazanmak",
  "Posture and desk pain": "Duruş ve masa ağrıları",
  "Full push-ups": "Tam şınav",
  "Plank for 30 seconds": "30 saniye plank",
  "Lunges": "Hamle",
  "Jumping (jacks, jumps)": "Zıplama (jumping jack, sıçrama)",
  "Knees": "Dizler",
  "Lower back": "Alt sırt",
  "Wrists": "Bilekler",
  "Shoulders": "Omuzlar",
  "Neck": "Boyun",
  "Too easy": "Çok kolay",
  "Just right": "Tam uygun",
  "Too hard": "Çok zor",
  "It hurt": "Acıttı",
  "Prefer not to say": "Belirtmek istemiyorum",
  "Female": "Kadın",
  "Male": "Erkek",
  "Metric (kg, cm)": "Metrik (kg, cm)",
  "Imperial (lb, in)": "İngiliz (lb, inç)",
  "All messages": "Tüm mesajlar",
  "Only important": "Sadece önemliler",
  "None": "Hiçbiri",
  "Monochrome": "Tek renk",
  "Signal": "Sinyal",
  "The server address must start with https:// (http:// only works for localhost).": "Sunucu adresi https:// ile başlamalı (http:// yalnızca localhost için çalışır).",
  "Last 7 days": "Son 7 gün",
  "Teal": "Turkuaz",
  "Violet": "Mor",
  "Rose": "Gül",
  "Blue": "Mavi",
  "Amber": "Kehribar",
  "after {n} seconds": "{n} saniye sonra",
  "{n} sets a day": "Günde {n} set",
  "Su": "Pz",
  "Mo": "Pt",
  "Tu": "Sa",
  "We": "Ça",
  "Th": "Pe",
  "Fr": "Cu",
  "Sa": "Ct",
  "Home": "Ana sayfa",
  "Stats": "İstatistik",
  "Board": "Sıralama",
  "Settings": "Ayarlar",
  "← Back": "← Geri",
  "Finish": "Bitir",
  "save": "kaydet",
  "join": "katıl",
  "restore": "geri yükle",
  "create": "oluştur",
  "Join": "Katıl",
  "Loading DeskFit…": "DeskFit yükleniyor…",
  "Loading…": "Yükleniyor…",
  "Open": "Aç",
  "Start a set": "Set başlat",
  "▶ Start a set": "▶ Set başlat",
  "Step {n} of {total}": "Adım {n} / {total}",
  "A stick figure warming up": "Isınan bir çubuk adam",
  "Short exercise breaks while Claude works. Everything stays on this device.": "Claude çalışırken kısa egzersiz molaları. Her şey bu cihazda kalır.",
  "DeskFit gives general fitness suggestions, not medical advice. Stop if anything hurts and check with a doctor if you have a health condition.": "DeskFit genel kondisyon önerileri verir, tıbbi tavsiye değildir. Bir yer acırsa dur; sağlık sorunun varsa doktoruna danış.",
  "Age": "Yaş",
  "e.g. 32": "örn. 32",
  "Body measurements tune set length and impact. They never leave this device.": "Vücut ölçülerin set süresini ve etkisini ayarlar. Bu cihazdan hiç çıkmaz.",
  "Weight (lb)": "Kilo (lb)",
  "Weight (kg)": "Kilo (kg)",
  "e.g. 160": "örn. 160",
  "e.g. 72": "örn. 72",
  "Height (in, optional)": "Boy (inç, isteğe bağlı)",
  "Height (cm, optional)": "Boy (cm, isteğe bağlı)",
  "e.g. 70": "örn. 70",
  "e.g. 178": "örn. 178",
  "Sex (only used for calorie estimates): ": "Cinsiyet (yalnızca kalori tahmini için): ",
  "Quiet mode (no jumping, good for open offices)": "Sessiz mod (zıplama yok, açık ofisler için uygun)",
  "DeskFit is for ages 16 to 90.": "DeskFit 16-90 yaş arası içindir.",
  "Weight should be 30 to 300 kg.": "Kilo 30 ile 300 kg arasında olmalı.",
  "Height should be 120 to 230 cm, or left empty.": "Boy 120 ile 230 cm arasında olmalı ya da boş bırakılmalı.",
  "You are set. {level} workouts are ready.": "Hazırsın. {level} seviyede antrenmanlar seni bekliyor.",
  "No set in progress.": "Devam eden set yok.",
  "In progress": "Devam ediyor",
  "Set {n} of {total}": "Set {n} / {total}",
  "set {n}/{total}": "set {n}/{total}",
  "{n}s": "{n} sn",
  "{name} demonstration": "{name} gösterimi",
  "Countdown timer": "Geri sayım",
  "Ready for {time}?": "{time} için hazır mısın?",
  "▶ Start": "▶ Başlat",
  "⇄ Another": "⇄ Başka",
  "✓ Finish now": "✓ Şimdi bitir",
  "✕ Cancel": "✕ İptal",
  "Workout": "Antrenman",
  "No finished set to show.": "Gösterilecek biten set yok.",
  "Set complete": "Set tamam",
  "Confetti": "Konfeti",
  "{name} · {secs}s · {kcal} kcal": "{name} · {secs} sn · {kcal} kcal",
  "+{xp} XP": "+{xp} XP",
  "{n} of {total} sets today": "Bugün {total} setten {n}",
  "{n}/{total} today": "Bugün {n}/{total}",
  "Streak": "Seri",
  "Daily goal reached · {n} day streak": "Günlük hedefe ulaşıldı · {n} günlük seri",
  "Level up: you are level {n}": "Seviye atladın: {n}. seviyedesin",
  "Badge unlocked": "Rozet açıldı",
  "Thanks, feedback saved.": "Teşekkürler, geri bildirimin kaydedildi.",
  "How was it?": "Nasıldı?",
  "▶ Next set": "▶ Sıradaki set",
  "✓ Done": "✓ Tamam",
  "Level {n}": "Seviye {n}",
  "{xp} XP to level {next}": "{next}. seviyeye {xp} XP",
  "{n} day streak": "{n} günlük seri",
  "Badges": "Rozetler",
  "{n}/{total} badges": "{n}/{total} rozet",
  "Today: {min} min · {kcal} kcal": "Bugün: {min} dk · {kcal} kcal",
  "Today": "Bugün",
  "Daily goal reached": "Günlük hedefe ulaşıldı",
  "Claude is working, a good moment for": "Claude çalışıyor, şunun için iyi bir an",
  "Up next": "Sıradaki",
  "⇄ Shuffle": "⇄ Karıştır",
  "This week": "Bu hafta",
  "Focus mode until {time}. No suggestions.": "Odak modu {time} saatine kadar. Öneri yok.",
  "Resting: {areas} (a week after a painful set)": "Dinleniyor: {areas} (acıtan setten sonra bir hafta)",
  "Stored only on this device. /workout focus 2h pauses suggestions.": "Yalnızca bu cihazda saklanır. /workout focus 2h önerileri durdurur.",
  "{n} d": "{n} g",
  "Your stats": "İstatistiklerin",
  "Level": "Seviye",
  "Best": "En iyi",
  "Sets": "Set",
  "Active min": "Aktif dk",
  "kcal": "kcal",
  "{xp} XP · level {next} at {at} · {sets} sets while Claude worked": "{xp} XP · {next}. seviye {at} XP'de · Claude çalışırken {sets} set",
  "This week: {min} min · {kcal} kcal": "Bu hafta: {min} dk · {kcal} kcal",
  "Sets per day": "Günlük set",
  "Sets per day over the last week": "Son haftada günlük set sayısı",
  "Active minutes per day": "Günlük aktif dakika",
  "Active minutes per day over the last week": "Son haftada günlük aktif dakika",
  "{min} min · {kcal} kcal": "{min} dk · {kcal} kcal",
  "No sets yet.": "Henüz set yok.",
  "Calories are active kcal (above resting), estimated from MET values in the 2024 Compendium of Physical Activities and your age, weight, height and sex. Treat them as rough: they can be off by 20-30%.": "Kaloriler aktif kcal'dir (dinlenmenin üzerinde); 2024 Fiziksel Aktiviteler Özeti'ndeki MET değerlerinden ve yaşın, kilon, boyun ve cinsiyetinden tahmin edilir. Yaklaşık değerler olarak düşün: %20-30 sapabilir.",
  "Badges {n}/{total}": "Rozetler {n}/{total}",
  "Badges, earned ones in colour": "Rozetler, kazanılanlar belirgin",
  "Profile": "Profil",
  "{n} years": "{n} yaş",
  "✎ Edit profile": "✎ Profili düzenle",
  "Workouts": "Antrenmanlar",
  "Daily goal": "Günlük hedef",
  "Quiet mode: no jumping or loud moves": "Sessiz mod: zıplama ve gürültülü hareket yok",
  "Suggest a set while Claude is working": "Claude çalışırken set öner",
  "Suggest": "Öneri",
  "How long Claude must be busy first.": "Claude'un önce ne kadar meşgul olması gerektiği.",
  "Look and sound": "Görünüm ve ses",
  "Accent colour": "Vurgu rengi",
  "Animations: moving figures and confetti": "Animasyonlar: hareketli figürler ve konfeti",
  "Sound effects": "Ses efektleri",
  "Play a test sound": "Deneme sesi çal",
  "Messages": "Mesajlar",
  "Pop-up notes like \"Set done\".": "\"Set tamam\" gibi açılır notlar.",
  "Show the DeskFit line above the prompt": "DeskFit satırını giriş kutusunun üstünde göster",
  "Language and units": "Dil ve birimler",
  "Language": "Dil",
  "More languages are planned.": "Daha fazla dil planlanıyor.",
  "Units": "Birimler",
  "Leaderboard": "Sıralama",
  "Server URL": "Sunucu adresi",
  "https://… (empty = off)": "https://… (boş = kapalı)",
  "Using {url}": "{url} kullanılıyor",
  "Only the public board is downloaded. Nothing about you is sent until you join.": "Yalnızca herkese açık tablo indirilir. Katılana kadar hakkında hiçbir şey gönderilmez.",
  "No server set: leaderboards are off and nothing leaves this device.": "Sunucu yok: sıralama kapalı ve hiçbir şey bu cihazdan çıkmaz.",
  "A company can host its own server; paste its URL here.": "Bir şirket kendi sunucusunu barındırabilir; adresini buraya yapıştır.",
  "Account ({name})": "Hesap ({name})",
  "Your data": "Verilerin",
  "Everything is stored on this device only, unless you joined a leaderboard.": "Bir sıralamaya katılmadıkça her şey yalnızca bu cihazda saklanır.",
  "Copy my data (JSON)": "Verilerimi kopyala (JSON)",
  "Erase everything…": "Her şeyi sil…",
  "Type /workout reset to erase all DeskFit data.": "Tüm DeskFit verilerini silmek için /workout reset yaz.",
  "Your data was copied to the clipboard.": "Verilerin panoya kopyalandı.",
  "Could not reach the clipboard here.": "Burada panoya erişilemedi.",
  "Leaderboards are off": "Sıralama kapalı",
  "Add a DeskFit server URL in Settings to compete on a public board or inside your company. DeskFit works fully without it.": "Herkese açık bir tabloda ya da şirketinde yarışmak için Ayarlar'dan bir DeskFit sunucu adresi ekle. DeskFit onsuz da tam çalışır.",
  "Open Settings": "Ayarları aç",
  "Join the leaderboard": "Sıralamaya katıl",
  "Shared: your nickname, points, sets and finish times. Never shared: age, weight, height, goal or health details. You can delete your account any time.": "Paylaşılanlar: takma adın, puanların, setlerin ve bitiş zamanları. Hiç paylaşılmayanlar: yaş, kilo, boy, hedef ve sağlık bilgileri. Hesabını istediğin zaman silebilirsin.",
  "Nickname": "Takma ad",
  "3-20 letters, digits, _ or -": "3-20 harf, rakam, _ veya -",
  "Or recovery code": "Ya da kurtarma kodu",
  "Account · {name}": "Hesap · {name}",
  "id {id} · data lives on this device and on {url}": "kimlik {id} · veriler bu cihazda ve {url} adresinde",
  "Recovery code (keep it private, it is the key to your account):": "Kurtarma kodu (gizli tut, hesabının anahtarıdır):",
  "Enter it on a new device under \"Or recovery code\" to restore your points and teams.": "Puanlarını ve takımlarını geri yüklemek için yeni cihazda \"Ya da kurtarma kodu\" alanına gir.",
  "Show recovery code": "Kurtarma kodunu göster",
  "Press again to delete everything": "Her şeyi silmek için tekrar bas",
  "Delete my leaderboard account": "Sıralama hesabımı sil",
  "Back to board": "Sıralamaya dön",
  "Account": "Hesap",
  "Weekly": "Haftalık",
  "All time": "Tüm zamanlar",
  "Teams": "Takımlar",
  "Leaderboard · {name}": "Sıralama · {name}",
  "{n} pts this week": "Bu hafta {n} puan",
  "↻ Refresh": "↻ Yenile",
  "You are not in a team yet. Create one or join with a code.": "Henüz bir takımda değilsin. Bir takım oluştur ya da kodla katıl.",
  "Invite code {code} · share it with teammates": "Davet kodu {code} · takım arkadaşlarınla paylaş",
  "Top three on the board": "Tablonun ilk üçü",
  "Nothing here yet": "Burada henüz bir şey yok",
  "No team board yet. Create a team or join with a code.": "Henüz takım tablosu yok. Bir takım oluştur ya da kodla katıl.",
  "No one has scored this period yet. Be first!": "Bu dönemde henüz kimse puan almadı. İlk sen ol!",
  "Rank {n}": "{n}. sıra",
  "{pts} pts · {sets} sets": "{pts} puan · {sets} set",
  "New team": "Yeni takım",
  "team name": "takım adı",
  "Join with code": "Kodla katıl",
  "8-character code": "8 karakterlik kod",
  "Leave {name}": "{name} takımından ayrıl",
  "Claude is working. {secs}s of {name}? Open /workout": "Claude çalışıyor. {secs} sn {name}? /workout aç",
  "Claude finished. Wrap up your set, then check the answer.": "Claude bitirdi. Setini tamamla, sonra cevaba bak.",
  "Daily goal done! {streak} day streak · +{xp} XP": "Günlük hedef tamam! {streak} günlük seri · +{xp} XP",
  "Set done · +{xp} XP": "Set tamam · +{xp} XP",
  "Skipping {area} moves for a week. If it keeps hurting, see a doctor.": "{area} hareketleri bir hafta atlanacak. Acı sürerse doktora git.",
  "Noted, next sets get a bit harder.": "Not aldım, sonraki setler biraz daha zor olacak.",
  "Noted, next sets get a bit easier.": "Not aldım, sonraki setler biraz daha kolay olacak.",
  "Claude is busy: {name}?": "Claude meşgul: {name}?",
  "DeskFit: type /workout to set up": "DeskFit: kurmak için /workout yaz",
  "DeskFit: micro-workouts while Claude works (/workout, stats, board, settings, focus 2h, reset)": "DeskFit: Claude çalışırken mini antrenmanlar (/workout, stats, board, settings, focus 2h, reset)",
  "DeskFit data erased from this device. Starting over.": "DeskFit verileri bu cihazdan silindi. Baştan başlıyoruz.",
  "Focus mode off. DeskFit may suggest sets again.": "Odak modu kapalı. DeskFit yeniden set önerebilir.",
  "Usage: /workout focus 90m, /workout focus 2h or /workout focus off": "Kullanım: /workout focus 90m, /workout focus 2h ya da /workout focus off",
  "Focus mode on for {time}. No suggestions until then.": "Odak modu {time} için açık. O zamana kadar öneri yok.",
  "DeskFit debug on: clicks and focus moves are logged.": "DeskFit hata ayıklama açık: tıklamalar ve odak hareketleri kaydediliyor.",
  "DeskFit debug off.": "DeskFit hata ayıklama kapalı.",
  "DeskFit opened.": "DeskFit açıldı.",
  "No backend is configured.": "Sunucu ayarlanmamış.",
  "Could not reach the leaderboard server.": "Sıralama sunucusuna ulaşılamadı.",
  "This device is not signed in anymore. Use your recovery code.": "Bu cihazın oturumu artık açık değil. Kurtarma kodunu kullan.",
  "Could not load the team board.": "Takım tablosu yüklenemedi.",
  "Could not load the leaderboard.": "Sıralama yüklenemedi.",
  "Nickname: 3-20 letters, digits, _ or -. Pick something that is not your real name.": "Takma ad: 3-20 harf, rakam, _ veya -. Gerçek adın olmayan bir şey seç.",
  "Sign-up failed.": "Kayıt başarısız.",
  "Welcome, {name}! Save your recovery code from Account.": "Hoş geldin, {name}! Kurtarma kodunu Hesap'tan kaydet.",
  "That recovery code is not valid.": "Bu kurtarma kodu geçerli değil.",
  "Recovery failed.": "Geri yükleme başarısız.",
  "Welcome back, {name}.": "Tekrar hoş geldin, {name}.",
  "Could not create the team.": "Takım oluşturulamadı.",
  "Team created. Invite code: {code}": "Takım oluşturuldu. Davet kodu: {code}",
  "Could not join the team.": "Takıma katılınamadı.",
  "Joined {name}.": "{name} takımına katıldın.",
  "You left the team.": "Takımdan ayrıldın.",
  "Could not leave.": "Ayrılınamadı.",
  "Could not delete the account.": "Hesap silinemedi.",
  "Your leaderboard account and its data were deleted.": "Sıralama hesabın ve verileri silindi.",
  "nickname taken": "Bu takma ad alınmış",
  "no team with that code": "Bu kodla bir takım yok",
  "too many sign-ups, try later": "Çok fazla kayıt denemesi, daha sonra tekrar dene",
  "you are in too many teams": "Çok fazla takımdasın",
  "team is full": "Takım dolu",
  "not a member": "Bu takımın üyesi değilsin",
  "unknown user": "Bilinmeyen kullanıcı",
  "bad signature": "Geçersiz imza",
  "replay": "Tekrarlanan istek",
  "clock skew": "Saat farkı çok büyük, cihaz saatini kontrol et",
  "missing credentials": "Kimlik bilgileri eksik",
  "bad json": "Geçersiz istek",
  "too large": "İstek çok büyük",
  "not found": "Bulunamadı",
  "nickname must be 3-20 letters, digits, _ or -": "Takma ad 3-20 harf, rakam, _ veya - olmalı",
  "team name must be 3-30 characters": "Takım adı 3-30 karakter olmalı",
  "bad secret": "Geçersiz anahtar",
  "Welcome to DeskFit": "DeskFit'e hoş geldin",
  "About you": "Senin hakkında",
  "Your body": "Vücudun",
  "Your goal": "Hedefin",
  "What you can do": "Neler yapabilirsin",
  "Your plan": "Planın",
  "Sets of about 30 seconds, right while Claude is busy.": "Claude meşgulken yaklaşık 30 saniyelik setler.",
  "A daily goal, streaks and badges keep you going.": "Günlük hedef, seriler ve rozetler seni motive eder.",
  "Your data never leaves this device unless you join a leaderboard.": "Bir sıralamaya katılmadıkça verilerin bu cihazdan çıkmaz.",
  "Your age and sex tune the intensity and the calorie estimates.": "Yaşın ve cinsiyetin yoğunluğu ve kalori tahminlerini ayarlar.",
  "Units: ": "Birimler: ",
  "Pick what matters most. It decides which moves come up more often.": "En önemlisini seç. Hangi hareketlerin daha sık çıkacağını belirler.",
  "Stay active and keep your energy up through the day.": "Gün boyu hareketli kal ve enerjini yüksek tut.",
  "More movement and more calories burned, steady and low impact.": "Daha fazla hareket ve daha çok kalori; düzenli ve düşük etkili.",
  "Build strength with push, leg and core work.": "İtme, bacak ve karın çalışmalarıyla güç kazan.",
  "Ease the neck, back and wrist strain from sitting.": "Oturmaktan kaynaklanan boyun, sırt ve bilek yükünü hafiflet.",
  "Moves you cannot do yet are left out, and so are moves that strain a sore spot.": "Henüz yapamadığın hareketler ve ağrılı bölgeni zorlayanlar listeye girmez.",
  "What can you do comfortably?": "Rahatça neleri yapabilirsin?",
  "Anything that bothers you?": "Seni rahatsız eden bir yer var mı?",
  "Each set takes about 30 to 40 seconds. You can change all of this later in Settings.": "Her set yaklaşık 30-40 saniye sürer. Bunların hepsini sonra Ayarlar'dan değiştirebilirsin.",
  "Get started": "Başla",
  "Next →": "İleri →",
  "{n} members · {pts} pts": "{n} üye · {pts} puan",
  "Copy code": "Kodu kopyala",
  "New code": "Yeni kod",
  "Close team…": "Takımı kapat…",
  "Press again to close the team": "Takımı kapatmak için tekrar bas",
  "Invite code copied.": "Davet kodu kopyalandı.",
  "New invite code: {code}": "Yeni davet kodu: {code}",
  "{name} was removed.": "{name} takımdan çıkarıldı.",
  "Team closed.": "Takım kapatıldı.",
  "Could not do that.": "Bu yapılamadı.",
  "Make a private board for your company or friends. Everyone who joins with your code sees the same scores, just in their own list.": "Şirketin ya da arkadaşların için özel bir tablo oluştur. Kodunla katılan herkes aynı puanları kendi listesinde görür.",
  "no such team": "Böyle bir takım yok",
  "only the team owner can do that": "Bunu yalnızca takım sahibi yapabilir",
  "no such member": "Böyle bir üye yok",
  "use leave to leave your own team": "Kendi takımından ayrılmak için Ayrıl'ı kullan",
  "could not make a new code": "Yeni kod üretilemedi",
  "no such user": "Böyle bir kullanıcı yok",
  "Seated leg extensions": "Oturarak bacak uzatma",
  "Seated figure-four stretch": "Oturarak dörtlü esnetme",
  "Standing quad stretch": "Ayakta ön bacak esnetme",
  "Standing glute kickbacks": "Ayakta kalça geri tekmeleme",
  "Wall push-ups": "Duvarda şınav",
  "Wall chest stretch": "Duvarda göğüs esnetme",
  "Overhead reach": "Yukarı uzanma",
  "Glute bridges": "Kalça köprüsü",
  "Crunches": "Mekik (crunch)",
  "Bicycle crunches": "Bisiklet crunch",
  "Leg raises": "Bacak kaldırma",
  "Sit-ups": "Mekik (sit-up)",
  "Supermans": "Superman",
  "Bird dogs": "Kuş-köpek",
  "Child's pose": "Çocuk pozu",
  "Downward dog": "Aşağı bakan köpek",
  "Knee push-ups": "Dizli şınav",
  "Plank shoulder taps": "Plankta omuz dokunuşu",
  "Inchworms": "Tırtıl",
  "Forward lunges": "İleri hamle",
  "High knees": "Yüksek diz çekme",
  "Dumbbell curls": "Dambıl bicep curl",
  "Dumbbell shoulder press": "Dambıl omuz press",
  "Goblet squats": "Goblet squat",
  "Bent-over dumbbell rows": "Eğilerek dambıl çekiş",
  "Dumbbell Romanian deadlifts": "Dambıl Romen deadlift",
  "Overhead triceps extensions": "Baş üstü triceps uzatma",
  "Seated band rows": "Oturarak bantla çekiş",
  "Band curls": "Bantla bicep curl",
  "Kettlebell swings": "Kettlebell sallama",
  "Pull-ups": "Barfiks",
  "Dead hang": "Barda asılma",
  "Sit tall, straighten one leg until it is level with the hip, hold a second, lower. Switch legs.": "Dik otur, bir bacağını kalça hizasına gelene kadar uzat, bir saniye tut, indir. Bacak değiştir.",
  "Sit tall, rest one ankle on the opposite knee and lean forward gently until you feel the hip stretch. Switch sides.": "Dik otur, bir ayak bileğini karşı dizine koy ve kalçada esneme hissedene kadar nazikçe öne eğil. Taraf değiştir.",
  "Hold the desk for balance, pull one heel toward your glutes with your knees together. Switch legs.": "Dengen için masaya tutun, dizlerin yan yana, bir topuğunu kalçana doğru çek. Bacak değiştir.",
  "Hold the desk, extend one leg straight back and squeeze your glute at the top. Switch legs.": "Masaya tutun, bir bacağını düz geriye uzat ve üstte kalçanı sık. Bacak değiştir.",
  "Hands on the wall at chest height, body in one line. Bend your elbows to bring your chest to the wall, then press back.": "Eller göğüs hizasında duvarda, vücut tek çizgide. Dirseklerini bükerek göğsünü duvara yaklaştır, sonra geri it.",
  "Place one forearm on a wall or door frame and turn away until you feel your chest open. Switch arms.": "Bir ön kolunu duvara ya da kapı pervazına koy ve göğsünün açıldığını hissedene kadar karşı yöne dön. Kol değiştir.",
  "Interlace your fingers, press your palms to the ceiling and reach up tall. Breathe, lower and repeat.": "Parmaklarını birleştir, avuçlarını tavana doğru it ve dikçe uzan. Nefes al, indir ve tekrarla.",
  "Lie on your back, knees bent, feet flat. Press through your heels to lift your hips, squeeze, then lower slowly.": "Sırtüstü uzan, dizler bükülü, tabanlar yerde. Topuklarından iterek kalçanı kaldır, sık, sonra yavaşça indir.",
  "Lie on your back, knees bent, hands behind your head. Curl your shoulders off the floor, then lower slowly.": "Sırtüstü uzan, dizler bükülü, eller başının arkasında. Omuzlarını yerden kaldır, sonra yavaşça indir.",
  "Lie back with your hands by your head. Bring one knee toward the opposite elbow while the other leg extends. Alternate smoothly.": "Sırtüstü uzan, elleri başının yanında tut. Bir dizini karşı dirseğe yaklaştır, diğer bacağın uzansın. Akıcı şekilde sırayla yap.",
  "Lie on your back with straight legs. Lift them to vertical, then lower slowly without arching your back.": "Sırtüstü uzan, bacaklar düz. Onları dikey konuma kaldır, sonra sırtını kavislemeden yavaşça indir.",
  "Lie on your back, knees bent. Curl all the way up to sitting, then lower with control.": "Sırtüstü uzan, dizler bükülü. Oturana kadar tamamen yuvarlanarak kalk, sonra kontrollü in.",
  "Lie face down with your arms forward. Lift arms, chest and legs a little off the floor, hold, then lower.": "Yüzüstü uzan, kollar ileride. Kolları, göğsü ve bacakları yerden biraz kaldır, tut, sonra indir.",
  "On hands and knees, reach one arm forward and the opposite leg back. Hold a second, then switch. Keep your hips level.": "Eller ve dizler üzerinde, bir kolunu ileri ve karşı bacağını geri uzat. Bir saniye tut, sonra değiştir. Kalçanı sabit tut.",
  "Kneel, sit back on your heels and reach your arms forward with your forehead down. Breathe slowly.": "Diz çök, topuklarının üstüne otur ve alnın yerde olacak şekilde kollarını ileri uzat. Yavaşça nefes al.",
  "Hands and feet on the floor, hips high in an upside-down V. Press the floor away and pedal your heels.": "Eller ve ayaklar yerde, kalçan yukarıda ters V şeklinde. Yeri it ve topuklarını sırayla pedal çevirir gibi oynat.",
  "Hands under shoulders, knees on the floor, body in one line from knees to head. Lower your chest, then press up.": "Eller omuz altında, dizler yerde, vücut dizden başa tek çizgide. Göğsünü indir, sonra yukarı it.",
  "High plank with feet wide. Tap one shoulder with the opposite hand while your hips stay still. Alternate.": "Ayaklar geniş yüksek plankta. Kalçan sabitken karşı elinle bir omzuna dokun. Sırayla yap.",
  "Stand, fold forward, walk your hands out to a plank, walk them back and stand up.": "Ayakta dur, öne eğil, ellerinle plank pozisyonuna yürü, geri yürü ve ayağa kalk.",
  "Step forward, lower your back knee toward the floor, then push back to standing. Alternate legs.": "İleri adım at, arka dizini yere doğru indir, sonra itip ayağa kalk. Bacakları değiştir.",
  "Run in place, driving your knees to hip height and pumping your arms.": "Yerinde koş, dizlerini kalça hizasına çek ve kollarını salla.",
  "Stand tall with your elbows at your sides. Curl the dumbbells to your shoulders and lower slowly.": "Dik dur, dirsekler gövdenin yanında. Dambılları omuzlarına kıvır ve yavaşça indir.",
  "Hold the dumbbells at shoulder height, press overhead until your arms are straight, then lower with control.": "Dambılları omuz hizasında tut, kollar düzleşene kadar başının üstüne it, sonra kontrollü indir.",
  "Hold one dumbbell at your chest, sit down between your knees with your chest tall, then stand up.": "Bir dambılı göğsünde tut, göğsün dik şekilde dizlerinin arasına çömel, sonra kalk.",
  "Hinge forward with a flat back and the dumbbells hanging. Pull your elbows back and squeeze your shoulder blades.": "Sırtın düz şekilde öne eğil, dambıllar aşağıda. Dirseklerini geriye çek ve kürek kemiklerini sık.",
  "Hold the dumbbells in front of your thighs. Push your hips back with a flat spine, lower to mid-shin, then stand tall.": "Dambılları uylukların önünde tut. Sırtın düz, kalçanı geriye it, kaval kemiği ortasına kadar indir, sonra dikleş.",
  "Hold one dumbbell overhead with both hands. Bend your elbows to lower it behind your head, then extend.": "Bir dambılı iki elinle başının üstünde tut. Dirseklerini bükerek başının arkasına indir, sonra uzat.",
  "Sit with your legs out and a band around your feet. Pull the band to your ribs, squeeze your shoulder blades, return slowly.": "Bacakların uzakta otur, bant ayaklarının etrafında. Bandı kaburgalarına çek, kürek kemiklerini sık, yavaşça geri bırak.",
  "Stand on the band with your elbows at your sides. Curl your hands to your shoulders and lower slowly.": "Bandın üstüne bas, dirsekler gövdenin yanında. Ellerini omuzlarına kıvır ve yavaşça indir.",
  "Hinge at the hips and hike the kettlebell back, then snap your hips forward to swing it to chest height.": "Kalçandan eğil ve kettlebell'i geriye salla, sonra kalçanı hızla öne iterek göğüs hizasına kadar savur.",
  "Hang from the bar with straight arms. Pull until your chin passes the bar, then lower under control.": "Kollar düz şekilde bara asıl. Çenen barı geçene kadar çek, sonra kontrollü in.",
  "Hang from the bar with relaxed shoulders and a firm grip. Breathe and let your spine lengthen.": "Omuzlar gevşek, tutuş sağlam şekilde bara asıl. Nefes al ve omurganın uzamasına izin ver.",
  "Office": "Ofis",
  "At home": "Evde",
  "Dumbbells": "Dambıl",
  "Resistance band": "Direnç bandı",
  "Kettlebell": "Kettlebell",
  "Pull-up bar": "Barfiks barı",
  "Exercise mat": "Egzersiz matı",
  "Where you train": "Nerede çalışıyorsun",
  "Where do you work out?": "Nerede egzersiz yapıyorsun?",
  "Gear you have": "Sahip olduğun ekipman",
  "Moves are picked to fit the room. Tell DeskFit where you train and what gear you own.": "Hareketler ortama göre seçilir. DeskFit'e nerede çalıştığını ve hangi ekipmanın olduğunu söyle.",
  "Office: quiet, small moves with a chair, desk or wall; a resistance band works too. Home: floor work, bigger moves, dumbbells, a kettlebell or a pull-up bar.": "Ofis: sandalye, masa ya da duvarla sessiz, küçük hareketler; lastik bant da olur. Ev: yer hareketleri, büyük hareketler, dambıl, kettlebell ya da barfiks demiri.",
  "Your dumbbells, kettlebell or bar are only used for home moves. Turn on At home to use them.": "Dambıl, kettlebell ve barfiks demiri sadece ev hareketlerinde kullanılır. Kullanmak için Evde seçeneğini aç.",
  "No gear is fine: there are plenty of moves without any.": "Ekipman olmasa da olur: ekipmansız bir sürü hareket var.",
  "Pick at least one place.": "En az bir yer seç.",
  "Where are you?": "Neredesin?",
  "Place and gear": "Yer ve ekipman",
  "Illustrations": "İllüstrasyonlar",
  "Stick figure": "Çubuk adam",
  "Abstract": "Soyut",
  "Line art": "Çizgi sanat",
  "Line art by Bryl Lim, based on Everkinetic (CC BY-SA 4.0). Moves without a drawing show none.": "Çizgi sanat: Bryl Lim, Everkinetic çizimlerine dayanır (CC BY-SA 4.0). Çizimi olmayan hareketlerde görsel gösterilmez."  ,
  "Neck and eyes": "Boyun ve gözler",
  "Shoulders and chest": "Omuz ve göğüs",
  "Back": "Sırt",
  "Arms": "Kollar",
  "Core": "Karın ve bel",
  "Hips and glutes": "Kalça",
  "Thighs": "Üst bacak",
  "Calves": "Baldır",
  "Strength": "Kuvvet",
  "Cardio": "Kardiyo",
  "Mobility": "Esneklik",
  "Stretch": "Germe",
  "light": "hafif",
  "moderate": "orta",
  "intense": "yoğun",
  "You asked for extra {region} work": "Ekstra {region} çalışması istemiştin",
  "Your {region} is behind this week": "Bu hafta {region} geride kaldı",
  "An easy one after the hard set": "Zor setten sonra kolay bir hareket",
  "A gentle start to the day": "Güne yumuşak bir başlangıç",
  "Keeps your week balanced": "Haftanı dengeli tutar",
  "Then: {moves}": "Sonra: {moves}",
  "Focus regions": "Odak bölgeleri",
  "Picked regions get extra weight when DeskFit chooses your next move. Leave empty to follow your goal.": "Seçtiğin bölgeler, sıradaki hareketi seçerken ek ağırlık alır. Hedefini izlemek için boş bırak.",
  "This week by body region": "Bu hafta vücut bölgelerine göre",
  "Share of this week by body region, with your goal share marked": "Bu haftanın bölgelere dağılımı, hedef payın işaretli",
  "The tick is your goal share. Highlighted regions are behind, and the next moves favour them.": "Çizgi hedef payındır. Vurgulu bölgeler geride, sıradaki hareketler onları öne çıkarır.",
  "All": "Tümü",
  "All moves": "Tüm hareketler",
  "Moves": "Hareketler",
  "Anywhere": "Her yer",
  "{n} moves": "{n} hareket",
  "Only what fits my plan": "Sadece planıma uyanlar",
  "Fits your plan": "Planına uyuyor",
  "Not in your plan": "Planında değil",
  "Home only": "Sadece evde",
  "Office only": "Sadece ofiste",
  "Office and home": "Ofis ve ev",
  "Needs {gear}": "Gerekli: {gear}",
  "Needs {ability}": "Gerekli: {ability}",
  "Hard on your {limit}": "{limit} için zorlayıcı",
  "Too advanced for now": "Şimdilik fazla zor",
  "Not quiet": "Sessiz değil",
  "High impact": "Yüksek darbeli",
  "Resting after a painful set": "Acıtan setten sonra dinleniyor",
  "Show more ({n} left)": "Daha fazla göster ({n} kaldı)",
  "▶ Try it": "▶ Dene",
  "Wall calf stretch": "Duvarda baldır germe",
  "Hands on a wall, one foot back with the heel down and the leg straight. Lean in until you feel the calf stretch. Switch legs.": "Ellerin duvarda, bir ayağın geride, topuk yerde ve bacak dik. Baldırında germe hissedene kadar öne eğil. Bacak değiştir.",
  "Shoulder-blade squeezes": "Kürek kemiği sıkıştırma",
  "Sit tall with your elbows bent. Pull your elbows back and squeeze your shoulder blades together for 2 seconds, then release.": "Dik otur, dirseklerin bükülü olsun. Dirseklerini geriye çek, kürek kemiklerini 2 saniye birbirine sıkıştır, bırak.",
  "Standing Y raises": "Ayakta Y kaldırma",
  "Stand tall with your arms low in front. Lift them overhead in a Y shape, thumbs up, squeezing your shoulder blades, then lower slowly.": "Dik dur, kollar önde aşağıda. Kollarını başının üstüne Y şeklinde kaldır, başparmaklar yukarıda, kürek kemiklerini sık, yavaşça indir."
}
